name: Publish
on:
  push:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Build and push Docker image to Github Packages
        uses: docker/build-push-action@v1.1.0
        with:
          username: mwingfield
          password: ${{ secrets.DOCKER_HUB_API_KEY }}
          repository: "bitdecaygames/limebuild"
          tags: "latest"
